var chinese = {
    "name": {
        "version": "2.0",
        "date": "2017-05-31",
        "name": "zh"
    },
    "IOS":{
    "TT_SYSTEMUNLINK": "打印机未连接",
    "TT_SYSTEMERROR": "未初始化",
    "TT_PREPARED": "打印机准备就绪",
    "TT_RUNING": "打印中",
    "TT_PAUSE": "暂停打印",
    "TT_NOZZLEERROR": "喷嘴错误",
    "TT_MOTIONERROR": "运动系统错误",
    "TT_FINISHED": "打印完成",
    "TT_USERSTOP": "打印被停止",
    "TT_TEMPHIGH": "喷嘴温度过高",
    "TT_TEMPLOW": "喷嘴温度过低",
    "TT_WORKROOMHIGH": "平台温度过高",
    "TT_REVERSE_1": "reverse_1",
    "TT_REVERSE_2": "reverse_2",
    "TT_REVERSE_3": "reverse_3",
    "TT_REVERSE_4": "reverse_4",
    "TT_SYSTEMPOWERON": "系统上电",
    "TT_SDCARDERROR": "SD卡错误",
    "TT_SDWBERROR": "SD卡写入错误",
    "TT_SDRBERROR": "SD卡读取错误",
    "TT_SAVETOSD": "保存打印数据至SD卡",
    "TT_JOGCMDERROR": "移动指令错误",
    "TT_COPYRIGHTZERO": "版权限制",
    "TT_PRINTTIMELIMIT": "打印次数限制",
    "TT_COMMERROR": "通讯错误",
    "Please_choose_a_printer": "请选择打印机",
    "Locals": "本地模型",
    "Featured": "精品模型",
    "More": "更多",
    "Library": "模型库",
    "DIY": "DIY",
    "Printer": "打印机",
    "Account": "账户",
    "Delete": "删除",
    "To_print":"去打印",
    "Select_All": "全选",
    "Cancel": "取消",
    "Delete_Selected_Models": "确定要删除所选模型？",
    "Confirm": "确定",
    "Purchased": "已购买",
    "Like_end": "已收藏",
    "Private": "已上传",
    "Published": "已发布",
    "Navigation": "导航",
    "Price": "价格",
    "All": "全部",
    "Pay_Models": "收费",
    "Free_Models": "免费",
    "Filter": "筛选",
    "Points": "积分",
    "Publish": "发布",
    "Name": "名称",
    "Unlimited": "无限制",
    "Category": "类别",
    "Size": "大小",
    "Details": "查看详情",
    "Download_All": "下载全部",
    "Like": "收藏",
    "Buy": "购买",
    "UnPublish": "取消发布",
    "Printer_Status": "打印机状态",
    "Process": "操作",
    "Maintenance": "维护",
    "Material": "材料",
    "Weight": "重量",
    "Extrude": "挤丝",
    "Withdraw": "撤丝",
    "Stop_Work": "停止工作",
    "Printer_List": "打印机列表",
    "Please_Enter": "请输入",
    "Please_Enter_Password": "请输入密码",
    "Connecting": "连接中……",
    "Failed_to_Connect": "连接失败",
    "Reprint": "重复打印",
    "Pause": "暂停打印",
    "Resume": "恢复打印",
    "Initalize_Printer": "初始化打印机",
    "Customized_Material": "自定义材料",
    "Nozzle": "喷嘴温度(℃)",
    "Platform": "底板温度(℃)",
    "Not_Logged_in": "未登录",
    "My_Printer": "我的打印机",
    "Settings": "设置",
    "Username_or_Email": "用户名/邮箱",
    "Password": "密码",
    "Login": "登录",
    "Forgot_Password": "忘记密码",
    "Sign_Up": "注册",
    "Register_Username": "用户名 (3-20个字符，以英文子母开头)",
    "Register_Email": "邮箱 (请输入正确邮箱)",
    "Register_Password": "密码(6-32个字符)",
    "Register_ConPassword": "确认密码(请再次输入密码)",
    "Register_Exist_Username": "用户名已存在",
    "Register_Exist_Email": "邮箱已存在",
    "Register_Error_Username": "用户名格式错误",
    "Register_Error_Email": "邮箱格式错误",
    "Register_Error_Password": "密码格式错误",
    "Register_Error_ConPassword": "密码不一致",
    "Register_Check_Params": "请检查输入参数",
    "Register_Success_Text": "注册成功！激活邮件已发送至邮箱，请激活帐号。",
    "ResetPassword_Fial": "用户名或邮箱错误",
    "ResetPassword_Success": "重置密码邮件发送成功",
    "All_Printers": "所有打印机",
    "Printer_Models": "打印机类型",
    "MyPrinter_CheckModel_Fail": "识别失败",
    "Serial_Number": "SN号",
    "Status": "状态",
    "Activation_Status": "激活状态",
    "Binding_Status": "绑定状态",
    "Activate_end": "已激活",
    "Unactivated": "未激活",
    "Activate": "激活",
    "Unbind": "解除绑定",
    "Bind": "绑定",
    "Privacy_Policy": "用户体验计划",
    "Clean_Up_Cache": "清理手机空间",
    "Sign_Out": "退出登录",
    "Infill": "填充",
    "Layer_Thickness": "层厚",
    "Quality": "质量",
    "Preview": "预览",
    "Print": "打印",
    "Shell": "壳",
    "Surface": "表面",
    "Please_Choose": "请选择",
    "Normal": "默认",
    "Fine": "较好",
    "Fast": "较快",
    "Turbo": "极快",
    "H": "H",
    "M": "M",
    "S": "S",
    "g": "g",
    "NoticeText_SliceError": "错误：分层错误",
    "Progress": "进度",
    "Initializing": "初始化中…",
    "Use_Camera": "拍照",
    "Album": "本地相册",
    "NoticeText_OutBound": "错误：模型超出打印范围",
    "NoticeText_NozzHeight": "错误：喷嘴高度错误，范围：",
    "NoticeText_PrintRun": "打印机运行中，不能进行此操作",
    "NoticeText_NoRepeatData": "没有可供重复打印的模型纪录",
    "NoticeText_TransError0": "传输未完成",
    "NoticeText_TransError1": "系统未准备就绪",
    "NoticeText_TransError2": "模型有空层",
    "NoticeText_TransError3": "模型材料不足",
    "NoticeText_TransError4": "支撑材料不足",
    "NoticeText_TransError5": "发送cmd指令失败",
    "NoticeText_TransError6": "打印机错误",
    "NoticeText_TransError7": "加载程序失败",
    "NoticeText_TransError8": "wifi数据失败",
    "NoticeText_TransError9": "没有设置喷嘴和底板温度",
    "NoticeText_TransError10": "许可验证失败",
    "Failed_to_load_model": "模型错误，打开失败",
    "NoticeText_BuySuccess": "购买成功",
    "NoticeText_BuyFail": "购买失败，请重试",
    "NoticeText_BuyPointError": "积分不足",
    "NoticeText_PublishName": "请输入模型名称",
    "NoticeText_PublishPoint": "请输入纯数字",
    "No_data": "没有数据",
    "NoticeLink_NetworkError": "网络错误，请稍后重试",
    "NoticeLink_PasswordError": "错误：打印机密码错误",
    "NoticeLink_AlreadyConnected": "错误：其他用户已连接此打印机",
    "NoticeLink_NotCert": "错误：打印机未认证",
    "NoticeLink_ConnectFail": "不能连接打印机",
    "NoticeLink_NoRespone": "错误：打印机未响应",
    "NoticeLink_Busy": "打印机忙",
    "CustomMaterial_NameTips": "请输入1-5位字符的材料名（字母、数字和‘+’‘-’‘_’的组合）",
    "CustomMaterial_NameRepeat": "材料名称已存在",
    "CustomMaterial_TempTips": "请输入温度数值(℃)",
    "CustomMaterial_NozzleTempTips": "喷嘴温度不合法，请输入0-300的数字",
    "CustomMaterial_PlatTempTips": "底板温度不合法，请输入0-100的数字",
    "No_Printer_Found": "未搜索到打印机",
    "Printer_Status_Error": "错误：打印机状态错误",
    "Please_Connect_to_a_Printer": "请先连接打印机",
    "Please_Enter_an_EmailvAddress": "请输入邮箱",
    "Invalid_Email_Address": "邮箱地址无效",
    "Email_not_Valid_or_Failed_to_Send_Email": "邮箱不存在或邮件发送失败",
    "Failed_to_Pause_Print_Job": "暂停打印失败",
    "Failed_to_Resume_Print_Job": "恢复打印失败",
    "Confirm_to_stop_the_current_job": "是否停止？",
    "NoticeLink_CheckNetTip": "请检查网络，且确保App连接的路由与打印机一致!",
    "ActivateTip": "请及时激活打印机从而使用完整的打印机功能",
    "ActivateTip_ActivateFail": "激活状态错误，请返厂",
    "ActivateTip_ActivateSuccess": "激活成功，请重新启动打印机",
    "Please_Close_the_Front_Door": "请关闭前门板",
    "Print_Job_Stopped_at_Layer_Number": "打印任务停在第",
    "Resume_the_Print_Job": "层，是否恢复打印?",
    "Data_Transmission_Failed": "错误：数据传输失败，是否重试？",
    "Unnamed": "未命名",
    "Invalid_Activation_Key": "错误：激活码错误",
    "Factory_Activation_Status_Error": "错误：不是工厂激活状态",
    "Activation_Failed_Invalid_Activation_Key": "错误：激活失败，错误的激活码",
    "Activation_data_returned_from_server_failed": "错误：服务器返回信息解析JSON失败",
    "Server_failed_to_return_activation_code": "错误：从服务器返回激活码失败",
    "Failed_to_get_checksum_data_from_the_printer": "错误：从打印机得到校验码失败",
    "Failed_to_obtain_the_activation_status": "错误：获得激活状态失败",
    "Cannot_Use_Special_Characters": "不能使用特殊字符",
    "User_Does_not_Exist": "账户不存在",
    "Please_Enter_Username_or_Email": "请输入用户名/邮箱",
    "Please_Enter_Your_Password": "请输入密码",
    "User_Account_is_not_Activated": "账户未激活",
    "Pull_down_to_refresh": "下拉可以刷新",
    "Release_to_refresh": "松开立即刷新",
    "Refreshing": "正在刷新…",
    "Pull_up_to_load_more": "上拉可以加载更多数据",
    "Release_to_load": "松开立即加载更多数据",
    "Loading": "正在加载数据…",
    "No_Data": "没有数据",
    "Slicing_in_progress_Cannot_load_models": "正在分层，无法导入模型",
    "No_material_detected_Please_reload_material": "未检测到材料，请更换",
    "PrivacyText": "请查看 Tiertime 的隐私声明以了解有关如何使用发送到 Tiertime 的数据的详细信息 , 您可以选择是否对应用程序启用数据收集功能.",
    "Singlepass_printing": "单次打印积分",
    "Registration_meas_you_agree_with": "注册即表示您同意",
    "Tiertime_End_User_Agreement": "太尔时代用户协议",
    "Under_Review": "审核中",
    "Purchase_Type": "套餐类型",
    "Customized": "自定义",
    "Local_Pictures": "相册",
    "Take_a_picture": "相机",
    "Edit": "编辑",
    "Pen": "画笔",
    "Text": "文字",
    "Crop": "裁剪",
    "Frame": "相框",
    "Vase": "花瓶",
    "Puzzle":"拼图",
    "NA": "无",
    "Base_Height": "基地高度",
    "Model_Height": "模型高度",
    "Add_Text": "添加文字",
    "Click_to_Enter_Text": "点击输入文字",
    "Keyboard": "键盘",
    "Font": "字体",
    "Toggle_color": "黑白反转",
    "Upload": "上传",
    "Move": "移动",
    "Scale": "缩放",
    "Rotate": "旋转",
    "Initial_View": "初始化",
    "X": "X",
    "Y": "Y",
    "Z": "Z",
    "AboutUs": "关于我们",
    "Current_Version": "当前版本",
    "WeChat_Official_Account": "微信公众号",
    "Official_Website": "官方网址",
    "Software_License_Agreement": "软件许可使用协议",
    "Copyright_Text": "北京太尔时代科技有限公司 版权所有",
    "Color_change":"换色",
    "floor":"有底",
    "no_floor":"无底",
    "Punching":"打孔",
    "Adjustment":"调整",
    "ModelName":"模型名称",
    "UploadModel":"上传模型",
    "Width":"长",
    "Height":"宽",
    "Depth":"深度",
    "Input_Error":"请输入有效的字符",
    "ModelAdjustment":"三维调整",
    "The_model_does_not_exist":"模型不存在",
    "Binded":"已绑定",
    "Choose_material":"选择材料",
    "Material_name":"材料名称",
    "Please_enter_the_weight":"请输入重量",
    "Please_enter_a_valid_number":"请输入有效的数字",
    "Preview_print":"预览打印",
    "Slicing":"分层中",
    "Transport":"传输中",
    "Counting":"计算中",
    "Select_the_print_location":"选择打印位置",
    "Picture_editing":"图片编辑",
    "Single_print_points":"单次打印积分",
    "User_does_not_exist":"用户不存在",
    "Wrong_password":"密码错误",
    "Login_fail_Text":"登录失败，请稍后尝试",
    "Confirm_to_delete_the_cache":"是否确认清除缓存",
    "The_currently_connected_printer":"当前连接的打印机",
    "Printer_information":"打印机信息",
    "Tiertime_Privacy_Agreement":"太尔时代隐私协议",
    "Remaining_Prints":"剩余打印次数",
    "times":"次",
    "Successful_publish":"发布成功",
    "Action_failed_please_try_later":"操作失败，请稍后尝试",
    "Stop_Printing":"停止打印",
    "ErrorText_MaterialShortage":"打印材料不足，是否继续打印？",
    "ErrorText_SupportShortage":"支撑材料不足，是否继续打印？",
    "ErrorText_TransferFailed":"数据传输失败，是否重试？",
    "ErrorText_UnknowError":"未知错误",
    "Print_Time":"打印耗时:",
    "Material_Consumption":"材料消耗:",
    "ErrorText_IncorrectMaterial":"打印机材料设置错误",
    "ErrorText_Printer_SN_Error":"打印机序列号有问题",
    "Join":"加入",
    "Package":"模型包",
    "Progress_Rate":"进度",
    "Import_Successful":"模型导入完成，是否打开？",
    "Open":"打开",
    "OpenFail_Slice":"载入模型失败，分层中不能载入其他模型！",
    "OpenFail_Trans":"载入模型失败，传输中不能载入其他模型！",
    "RegisterFail_hasExist":"注册失败，用户名或邮箱已存在！",
    "No_network":"无网络连接，请先连接网络。",
    "Error_ModelData":"转换失败，模型数据为0",
    "Demonstration":"演示",
    "ModelSaveFailed":"模型保存失败，请重试!"
}
}